# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
jobs:
    test:
        docker:
            - image: cimg/node:lts-browsers
        working_directory: ~/repo
        resource_class: large
        steps:
            - checkout

            - run:
                  name: Yarn version
                  command: yarn --version

            # Download and cache dependencies (Yarn artifacts, not node_modules)
            - restore_cache:
                  keys:
                      - v3-yarn-{{ checksum "yarn.lock" }}
                      - v3-yarn-
            - run:
                  name: Install dependencies (immutable)
                  command: yarn install --immutable
            - save_cache:
                  paths:
                      - .yarn/cache
                      - .yarn/releases
                      - .yarn/plugins
                      - .yarn/patches
                  key: v3-yarn-{{ checksum "yarn.lock" }}

            - run:
                  name: Install dependencies
                  command: yarn install

            - run:
                  name: Test Jest
                  command: make test-jest

            - store_test_results:
                  path: test_reports

    test-react:
        docker:
            - image: cimg/node:lts-browsers
        working_directory: ~/repo
        parallelism: 6
        resource_class: large
        steps:
            - checkout

            - run:
                  name: Yarn version
                  command: yarn --version

            - restore_cache:
                  keys:
                      - v3-yarn-{{ checksum "yarn.lock" }}
                      - v3-yarn-
            - run:
                  name: Install dependencies (immutable)
                  command: yarn install --immutable
            - save_cache:
                  paths:
                      - .yarn/cache
                      - .yarn/releases
                      - .yarn/plugins
                      - .yarn/patches
                  key: v3-yarn-{{ checksum "yarn.lock" }}

            - run:
                  name: Install dependencies
                  command: yarn install

            - run:
                  name: React tests
                  command: make test-react
                  environment:
                      JEST_JUNIT_OUTPUT: test_reports/framer-motion-react.xml

            - store_test_results:
                  path: test_reports

    test-react-19:
        docker:
            - image: cimg/node:lts-browsers
        working_directory: ~/repo
        parallelism: 6
        resource_class: large
        steps:
            - checkout

            - run:
                  name: Yarn version
                  command: yarn --version

            - restore_cache:
                  keys:
                      - v3-yarn-{{ checksum "yarn.lock" }}
                      - v3-yarn-
            - run:
                  name: Install dependencies (immutable)
                  command: yarn install --immutable
            - save_cache:
                  paths:
                      - .yarn/cache
                      - .yarn/releases
                      - .yarn/plugins
                      - .yarn/patches
                  key: v3-yarn-{{ checksum "yarn.lock" }}

            - run:
                  name: Install dependencies
                  command: yarn install

            - run:
                  name: React tests
                  command: make test-react-19
                  environment:
                      JEST_JUNIT_OUTPUT: test_reports/framer-motion-react-19.xml

            - store_test_results:
                  path: test_reports

    test-html:
        docker:
            - image: cimg/node:lts-browsers
        resource_class: large
        working_directory: ~/repo
        steps:
            - checkout

            - run:
                  name: Yarn version
                  command: yarn --version

            - restore_cache:
                  keys:
                      - v3-yarn-{{ checksum "yarn.lock" }}
                      - v3-yarn-
            - run:
                  name: Install dependencies (immutable)
                  command: yarn install --immutable
            - save_cache:
                  paths:
                      - .yarn/cache
                      - .yarn/releases
                      - .yarn/plugins
                      - .yarn/patches
                  key: v3-yarn-{{ checksum "yarn.lock" }}

            - run:
                  name: Install dependencies
                  command: yarn install

            - run:
                  name: HTML tests
                  command: make test-html
                  environment:
                      JEST_JUNIT_OUTPUT: test_reports/framer-motion-html.xml

            - run:
                  name: Next.js tests
                  command: make test-nextjs
                  environment:
                      JEST_JUNIT_OUTPUT: test_reports/framer-motion-next.xml

            - store_test_results:
                  path: test_reports

    test-playwright:
        docker:
            - image: mcr.microsoft.com/playwright:v1.51.1-noble
        resource_class: large
        working_directory: ~/repo
        steps:
            - checkout

            - run:
                  name: Yarn version
                  command: yarn --version

            - restore_cache:
                  keys:
                      - v3-yarn-{{ checksum "yarn.lock" }}
                      - v3-yarn-
            - run:
                  name: Install dependencies (immutable)
                  command: yarn install --immutable
            - save_cache:
                  paths:
                      - .yarn/cache
                      - .yarn/releases
                      - .yarn/plugins
                      - .yarn/patches
                  key: v3-yarn-{{ checksum "yarn.lock" }}

            - run:
                  name: Install dependencies
                  command: yarn install

            - run:
                  name: Playwright tests
                  command: yarn test-playwright
                  environment:
                      JEST_JUNIT_OUTPUT: test_reports/framer-motion-playwright.xml

            - store_test_results:
                  path: test_reports

workflows:
    version: 2
    build:
        jobs:
            - test
            - test-react
            - test-html
