# .github/workflows/tag-update.yml
name: Send notification on tag update

on:
    push:
        tags:
            - "v*"
            - "*.*.*"

jobs:
    update-api:
        runs-on: ubuntu-latest

        steps:
            - name: Extract tag name
              id: tag
              run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

            - name: Send version to API
              run: |
                  curl -X POST \
                    -H 'Content-type: application/json' \
                    -H 'Authorization: Bearer ${{ secrets.API_TOKEN }}' \
                    -d '{"version": "${{ steps.tag.outputs.VERSION }}"}' \
                    http://api.motion.dev/slack/update
              env:
                  API_TOKEN: ${{ secrets.API_TOKEN }}
